restructure workflow

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -29,7 +29,6 @@ jobs:
 
     outputs:
       release_version: ${{ steps.setup_vars.outputs.release_version }}
-      app_name: ${{ steps.setup_vars.outputs.app_name }}
 
     steps:
       - name: Checkout
@@ -48,7 +47,6 @@ jobs:
           echo "RELEASE_YEAR=${YEAR}" >> $GITHUB_ENV
           echo "RELEASE_VERSION=${RELEASE_VERSION}" >> $GITHUB_ENV
           echo "release_version=${RELEASE_VERSION}" >> $GITHUB_OUTPUT
-          echo "app_name=${{ secrets.APP_NAME }}" >> $GITHUB_OUTPUT
           echo "Tag version: ${VERSION}"
           echo "Release year: ${YEAR}"
           echo "Full release version: ${RELEASE_VERSION}"
@@ -117,7 +115,7 @@ jobs:
 
     env:
       RELEASE_VERSION: ${{ needs.build.outputs.release_version }}
-      APP_NAME: ${{ needs.build.outputs.app_name }}
+      APP_NAME: ${{ secrets.APP_NAME }}
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
     steps:
@@ -130,32 +128,36 @@ jobs:
         id: prep_files
         shell: bash
         run: |
+          if [ -z "$APP_NAME" ]; then
+            echo "Error: APP_NAME environment variable is not set."
+            exit 1
+          fi
           mkdir release
           CHECKSUM_BODY_DATA="### Checksums\n\n| File | SHA256 |\n|---|---|\n"
           if [ -d dist/dist-linux ]; then
-            if [ -f dist/dist-linux/${APP_NAME} ]; then
-              mv dist/dist-linux/${APP_NAME} release/${APP_NAME}_${RELEASE_VERSION}_amd64
-              CHECKSUM_BODY_DATA+=$(sha256sum release/${APP_NAME}_${RELEASE_VERSION}_amd64 | awk '{print "| `" $2 "` | `" $1 "` |"}')"\n"
+            if [ -f "dist/dist-linux/${APP_NAME}" ]; then
+              mv "dist/dist-linux/${APP_NAME}" "release/${APP_NAME}_${RELEASE_VERSION}_amd64"
+              CHECKSUM_BODY_DATA+=$(sha256sum "release/${APP_NAME}_${RELEASE_VERSION}_amd64" | awk '{print "| `" $2 "` | `" $1 "` |"}')"\n"
             fi
           fi
           if [ -d dist/dist-windows ]; then
-            if [ -f dist/dist-windows/${APP_NAME} ]; then
-              mv dist/dist-windows/${APP_NAME} release/${APP_NAME}_${RELEASE_VERSION}_amd64.exe
-              CHECKSUM_BODY_DATA+=$(sha256sum release/${APP_NAME}_${RELEASE_VERSION}_amd64.exe | awk '{print "| `" $2 "` | `" $1 "` |"}')"\n"
+            if [ -f "dist/dist-windows/${APP_NAME}" ]; then
+              mv "dist/dist-windows/${APP_NAME}" "release/${APP_NAME}_${RELEASE_VERSION}_amd64.exe"
+              CHECKSUM_BODY_DATA+=$(sha256sum "release/${APP_NAME}_${RELEASE_VERSION}_amd64.exe" | awk '{print "| `" $2 "` | `" $1 "` |"}')"\n"
             fi
-            if [ -f dist/dist-windows/${APP_NAME}-amd64-installer.exe ]; then
-              mv dist/dist-windows/${APP_NAME}-amd64-installer.exe release/${APP_NAME}_${RELEASE_VERSION}_amd64_installer.exe
-              CHECKSUM_BODY_DATA+=$(sha256sum release/${APP_NAME}_${RELEASE_VERSION}_amd64_installer.exe | awk '{print "| `" $2 "` | `" $1 "` |"}')"\n"
+            if [ -f "dist/dist-windows/${APP_NAME}-amd64-installer.exe" ]; then
+              mv "dist/dist-windows/${APP_NAME}-amd64-installer.exe" "release/${APP_NAME}_${RELEASE_VERSION}_amd64_installer.exe"
+              CHECKSUM_BODY_DATA+=$(sha256sum "release/${APP_NAME}_${RELEASE_VERSION}_amd64_installer.exe" | awk '{print "| `" $2 "` | `" $1 "` |"}')"\n"
             fi
           fi
           if [ -d dist/dist-mac ]; then
-            if [ -f dist/dist-mac/${APP_NAME}.app.zip ]; then
-               mv dist/dist-mac/${APP_NAME}.app.zip release/${APP_NAME}_${RELEASE_VERSION}_universal.zip
-               CHECKSUM_BODY_DATA+=$(sha256sum release/${APP_NAME}_${RELEASE_VERSION}_universal.zip | awk '{print "| `" $2 "` | `" $1 "` |"}')"\n"
+            if [ -f "dist/dist-mac/${APP_NAME}.app.zip" ]; then
+               mv "dist/dist-mac/${APP_NAME}.app.zip" "release/${APP_NAME}_${RELEASE_VERSION}_universal.zip"
+               CHECKSUM_BODY_DATA+=$(sha256sum "release/${APP_NAME}_${RELEASE_VERSION}_universal.zip" | awk '{print "| `" $2 "` | `" $1 "` |"}')"\n"
             fi
-             if [ -f dist/dist-mac/${APP_NAME}.dmg ]; then
-               mv dist/dist-mac/${APP_NAME}.dmg release/${APP_NAME}_${RELEASE_VERSION}_universal.dmg
-               CHECKSUM_BODY_DATA+=$(sha256sum release/${APP_NAME}_${RELEASE_VERSION}_universal.dmg | awk '{print "| `" $2 "` | `" $1 "` |"}')"\n"
+             if [ -f "dist/dist-mac/${APP_NAME}.dmg" ]; then
+               mv "dist/dist-mac/${APP_NAME}.dmg" "release/${APP_NAME}_${RELEASE_VERSION}_universal.dmg"
+               CHECKSUM_BODY_DATA+=$(sha256sum "release/${APP_NAME}_${RELEASE_VERSION}_universal.dmg" | awk '{print "| `" $2 "` | `" $1 "` |"}')"\n"
             fi
           fi
           echo "checksum_list<<EOF" >> $GITHUB_OUTPUT
@@ -179,8 +181,7 @@ jobs:
         run: |
           if [ -z "$GPG_PRIVATE_KEY" ]; then
             echo "GPG_PRIVATE_KEY environment variable is not set or is empty. Skipping GPG steps."
-            # Set an output or state if you need subsequent steps to know GPG was skipped
-            echo "gpg_skipped=true" >> $GITHUB_ENV 
+            echo "gpg_skipped=true" >> $GITHUB_ENV
           else
             echo "GPG_PRIVATE_KEY is set. Attempting import..."
             echo "$GPG_PRIVATE_KEY" | base64 --decode | gpg --batch --import
